### ISSUE TITLE
Disk (MSFT_Disk): Opens Format Window

### ISSUE THREAD

**Issue by mwtilton** [PowerShell/StorageDsc#171]
#### Details 
When Running the above script the verbose output returns no error messages and finishes cleanly however the "Formatting Disk (E:)" window is opened upon "completion" of the other operations. This forces you to still select formatting options through the GUI instead of remain on the CLI

If you run the below cmdlets it all runs within the CLI.
```
Get-Partition -DriveLetter 'C' | Resize-Partition -Size 32GB
New-Partition -DiskNumber 1 -UseMaximumSize -DriveLetter 'E'
Format-Volume -DriveLetter 'E' -FileSystem NTFS -NewFileSystemLabel 'Data' -Full -Force
```

#### Verbose Output
Clean output no errors.
```
VERBOSE: [WIN-768UBAPULEL]: LCM:  [ End    Set      ]  [[Disk]EVolume]  in 3.8290 seconds.
VERBOSE: [WIN-768UBAPULEL]: LCM:  [ End    Resource ]  [[Disk]EVolume]
VERBOSE: [WIN-768UBAPULEL]: LCM:  [ End    Set      ]
VERBOSE: [WIN-768UBAPULEL]: LCM:  [ End    Set      ]    in  3.9380 seconds.
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 3.985 seconds
```

#### Suggested solution to the issue
Adding something like this to the "Default NTFS option"
```
$volParams = @{
            FileSystem = $FSFormat
            Confirm    = $false
            Force = $true
            Full = $true
}
```
or this...
```
if ($FSFull)
{
    # Set the File System label on the new volume
    $volParams["Full"] = $Full
} # if
if ($FSForce)
{
    # Set the File System label on the new volume
    $volParams["FSForce"] = $FSForce
} # if

```

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

```
configuration buildFileServer
{
    Import-DSCResource -ModuleName StorageDsc

    Node localhost
    {
        Disk EVolume
        {
             DiskId = 0
             DriveLetter = 'E'
             FSLabel = 'Data'
        }

    }
}
buildFileServer

Set-DSCLocalConfigurationManager -Path .\buildFileServer –Verbose
Start-DscConfiguration -Wait -Force -Path .\buildFileServer -Verbose
```

If I look at the source code it shows:
```
if ($volume.FileSystem -eq '')
    {
        # The volume is not formatted
        $volParams = @{
            FileSystem = $FSFormat
            Confirm    = $false
        }

        if ($FSLabel)
        {
            # Set the File System label on the new volume
            $volParams["NewFileSystemLabel"] = $FSLabel
        } # if

        if ($AllocationUnitSize)
        {
            # Set the Allocation Unit Size on the new volume
            $volParams["AllocationUnitSize"] = $AllocationUnitSize
        } # if

        Write-Verbose -Message ( @(
                "$($MyInvocation.MyCommand): "
                $($localizedData.FormattingVolumeMessage -f $volParams.FileSystem)
            ) -join '' )

        # Format the volume
        $volume = $partition | Format-Volume @VolParams
}
```
So it should return soimething like this if we "break out" the params from ``@volparams``
$volume = $partition | Format-Volume -NewFileSystemLabel 'Data' -FileSystem NTFS

But it does not have the ``-Force`` or ``-Full`` params, which I believe are the options that enforce the process to remain within the CLI

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2016 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
WindowsBuildLabEx    : 14393.0.amd64fre.rs1_release.160715-1616
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running
PSVersion: 5.1.14393.0
PSEdition: Desktop
PSCompatibleVersions: {1.0, 2.0, 3.0, 4.0...}
BuildVersion: 10.0.14393.0
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
Master

**Comment by mwtilton** [comment]
Looks like this was a similar issue to: #148
And I also tested with:
```
Get-Partition -DriveLetter 'C' | Resize-Partition -Size 32GB
New-Partition -DiskNumber 1 -UseMaximumSize -DriveLetter 'E'
Format-Volume -DriveLetter 'E' -FileSystem NTFS -NewFileSystemLabel 'Data' -Full
```
This will still bring up a prompt but allow the actual progress to be "tracked within the CLI

**Comment by PlagueHO** [comment]
I have noticed this during integration tests and should be resolved if possible - although it doesn't seem to cause a failure. It should be easy enough to fix using your suggested code. I've got one PR going through at the moment so I'll include your code after that (unless you want to submit a PR?) .

**Comment by mwtilton** [comment]
Whatever works easiest for you :)

**Comment by johlju** [comment]
Using `Format-Volume` with `Full` will actually write to every byte on the disk, and is not recommended when using thin provisioning. So using `Full` says that it should not use quick-format. 

The GUI that pops up, isn't that just the GUI is to quick to find the disk will it still isn't reported as formatted? Isn't it a GUI "bug" and not a problem with running the cmdlets? 🤔

**Comment by mwtilton** [comment]
I am currently use "Thick" provisioning for my VM's so I think `-Full` is the better option in the long run, I could definitely be wrong though... :)

But I'm betting to help those who do not use "Thick" provisioning there should be the option to turn it "on/off"
```
Disk EVolume
{
     Full = $true
}
```

You can add in the `-Confirm` parameter and it should suppress the gui window. Still testing as it seems it may not work in conjunction with the `-Force` parameter. But I'll update on that once I get more information.
